export const USER_ROLES = Object.freeze({
  CUSTOMER: 'CUSTOMER',
  CLIENT: 'CLIENT',
  FMG: 'FMG',
  CARRIER: 'CARRIER',
});

export const CLAIM_STATUSES = Object.freeze({
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  MANUAL_REVIEW: 'MANUAL_REVIEW',
  PAYMENT_COMPLETED: 'PAYMENT_COMPLETED',
});

export const CLAIM_STAGES = Object.freeze({
  CUSTOMER: 'CUSTOMER',
  CLIENT: 'CLIENT',
  FMG: 'FMG',
  CARRIER: 'CARRIER',
  COMPLETED: 'COMPLETED',
});

export const POLICY_TYPES = Object.freeze({
  HEALTH: 'HEALTH',
  LIFE: 'LIFE',
  AD_AND_D: 'AD_AND_D',
  CRITICAL_ILLNESS: 'CRITICAL_ILLNESS',
});
