spring.application.name=tpa-claim-process-api

server.port=${SERVER_PORT:8080}
server.servlet.context-path=${SERVER_SERVLET_CONTEXT_PATH:/api/v1}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/tpa_claims}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:tpa_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:tpa_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_schema=${SPRING_JPA_DEFAULT_SCHEMA:claim_schema}

spring.sql.init.mode=${SPRING_SQL_INIT_MODE:never}

tpa.api.version=${TPA_API_VERSION:v1}
tpa.api.title=${TPA_API_TITLE:TPA Claim Processing API}
